### PR TITLE
Updated Faraday to 1.0.0

### PR DESCRIPTION
**Pull request by bidluo**
The current version (0.15.4) is out of date and doesn't fully support Ruby 2.7.
This change is primarily targeted to fix the deprecation warnings from faraday.

### CODE REVIEW

**Comment by sabman** [comment]
Thanks @bidluo can we also add `2.7` to the travis-ci?

**Comment by bidluo** [comment]
@sabman done but looks like Faraday depends on `ruby >= 2.3` (and fcm is `ruby >= 2.0.0`) so I think this will be up to you/maintainers to decide the outcome of this PR

**Comment by sabman** [comment]
might be time to get a new minor release `0.1.0` with only `ruby 2.4+` support. What do the others? @kashif?

**Comment by sabman** [comment]
or better still a major version release `1.0.0`. otherwise people might accidentally upgrade and break stuff.

**Comment by kashif** [comment]
👍

**Comment by v-kolesnikov** [comment]
@bidluo @bidluo  Hi guys! Could I help you with this work? What the trouble?

**Comment by bidluo** [comment]
@v-kolesnikov Nah seems fine, needs maintainers you merge

**Comment by sabman** [comment]
OK gonna merge this and make a new major release

**Comment by dankimio** [comment]
@sabman Any updates? Can we at least publish a beta version of 1.0?

**Comment by sabman** [comment]
Sorry for the delay. I'll make an attempt at cutting a gem today (in a
couple of hours).

**Comment by dankimio** [comment]
@sabman I could help with this if can add me to the repo and RubyGems

**Comment by sabman** [comment]
@dankimio I've pushed a release but we've added you to the team as well, thanks again for your patience

**Pull request merged**
