### PR TITLE
Added send_to_condition method, to send notifications via conditions. 

### PR DESCRIPTION
**Pull request by patricks**

### CODE REVIEW

**Comment by kashif** [comment]
cool thanks! will look shortly and merge

**Comment by BastianHofmann** [comment]
@kashif What's the status on this?

**Comment by anmolarora** [comment]
@kashif Any development in merging this PR?

**Comment by sabman** [comment]
@patricks are you able to add a test/spec for this?

**Comment by patricks** [comment]
@sabman I am currently out of this project sry. 😥

**Pull request closed without merging**
